Lesson 10 complete
smalew/qna pull request #12
Opened 2020-07-31 20:32 UTC by smalew

2020-08-01 09:33 UTC, vkurennov requested changes

2020-08-01 09:33 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +      positives: record.rates.positives.count,
зачем отдельно передавать положительные и отрицательные голоса? передавай сразу сумму, тем более, что эти атрибуты, похоже, вообще на клиенте не используются

2020-08-01 09:33 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +      status: 200,
статус не внутри json передается, а отдельным параметром. так что смысла здесь передавать статуст нет, он по-умолчанию 200

2020-08-01 09:33 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +      positives: record.rates.positives.count,
это относится и к остальным экшенам.

2020-08-01 09:33 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +    render json: {
дублирование, можно вынести формирование ответа в приватный метод

2020-08-01 09:33 UTC, vkurennov commented on app/models/concerns/ratable.rb
> +    rates.positives.count - rates.negatives.count
не очень удачная схема хранения голосов. зачем делать их true/false, если можно хранить +/- 1 и тогда, используя метод sum у ассоциации, можно выполнить агрегатный запрос на суммирование и база сразу вернет итог. так будет всего 1 запрос, вместо двух

2020-08-02 15:25 UTC, smalew commented on app/controllers/concerns/rated.rb
> +      positives: record.rates.positives.count,
Моей идеей было, что я буду считать разность на фронте, но в ходе написания функционала это стало неактуально. 

Переделал.

2020-08-02 15:26 UTC, smalew commented on app/controllers/concerns/rated.rb
> +      status: 200,
Точно. Что-то я тут недоглядел. Убрал.

2020-08-02 15:26 UTC, smalew commented on app/controllers/concerns/rated.rb
> +    render json: {
Сделал

2020-08-02 15:27 UTC, smalew commented on app/models/concerns/ratable.rb
> +    rates.positives.count - rates.negatives.count
Я исходил из того, что просто поле `value` в таблице `rates` слишком абстракно. 

Переделал.

2020-08-03 10:09 UTC, vkurennov approved these changes

2020-08-03 17:22 UTC, merged