Lesson 11
smalew/qna pull request #13
Opened 2020-08-12 19:05 UTC by smalew

С применением ActionCable реализовать следующее:
При добавлении ответа к вопросу, этот ответ должен появиться у всех пользователей, у которых открыт этот вопрос
При добавлении нового вопроса, у всех пользователей, у которых открыт список вопросов, должен появиться новый вопрос в списке
Пользователь может добавлять комментарии к вопросам/ответам (не использовать сторнние гемы)
При добавлении комментария, он должен появиться у всех пользователей, у которых открыта страница с тем же вопросом.

2020-08-13 10:47 UTC, vkurennov requested changes

2020-08-13 10:47 UTC, vkurennov commented on app/channels/comments_channel.rb
> +    stream_for "comments_#{params[:record_type]}_#{params[:record_id]}"
особого смысла делать стримы еще и для каждого типа объекта нет, более того, это лишние ресурсы тратит. Достаточно отделять по question_id, чтобы на страницу вопроса был один стрим для комментариев, а тип и id объекта, за который отдан коммент, отправлять с сервера

2020-08-13 10:47 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    gon.answer_ids = answers.map(&:id) << answer.id if answer.errors.blank?
не думаю, что это хорошая идея - хранить id всех вообще ответов на клиенте. а если это супер-популярный вопрос, с кучей ответов? ну и через map доставать id-ки так себе идея, для ассоциаций как раз есть метод answer_ids, который сразу из базы и вернет все id, это быстрее и менее затратно по памяти.

2020-08-13 10:47 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      'answers',
не нужно делать универсальный стрим для всех ответов, надо разделять по question_id, т.к. иначе в этот стрим будут сыпаться вобще все ответы, и, видимо, для этого тебе и нужно на клиенте знать id ответов у конкретного вопроса. Но это дважды не оптимально (сначала на сервере проход по id, потом на клиенте).
Раздели стрим по question_id и тогда на один вопрос будет один стрим для ответов и все ответы, приходящие в него будут заведомо к этому вопросу и не нужно будет ничего искать.

2020-08-13 10:47 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    gon.answer_ids = answers.map(&:id)
избавься от этого, как - описал выше

2020-08-13 10:47 UTC, vkurennov commented on app/javascript/channels/answer_comments_channel.js
> +    gon.answer_ids.forEach(function (answer_id) {
можно обойтись одним стримом для всех комментариев на странице одного вопроса. создавать кучу подписок на одной странице - тратить ресурсы браузера (читай - процессора, памяти, батареи)

2020-08-13 18:06 UTC, smalew commented on app/channels/comments_channel.rb
> +    stream_for "comments_#{params[:record_type]}_#{params[:record_id]}"
Ну точно же. Что-то я не в ту сторону загнался. Решил, что хорошей идеей будет "слушать" каждый объект на странице. 

Хотя понимал же что это отжирает соединения и ресурсы. ну зато поразбирался как это в принципе работает и тестируется. )

Поправил.

2020-08-13 18:08 UTC, smalew commented on app/controllers/answers_controller.rb
> +    gon.answer_ids = answers.map(&:id) << answer.id if answer.errors.blank?
После доработок стало неактуально. Удалил. 

map(&:id) использовал как-раз для того, что бы не делать еще один запрос в БД, а забрать их из памяти. 
Вроде же это менее затратнее, чем делать еще один запрос?

2020-08-13 18:18 UTC, smalew commented on app/controllers/answers_controller.rb
> +      'answers',
Отличное замечание. Переделал на стрим для каждого вопроса.

2020-08-13 18:19 UTC, smalew commented on app/controllers/questions_controller.rb
> +    gon.answer_ids = answers.map(&:id)
Готово

2020-08-13 18:19 UTC, smalew commented on app/javascript/channels/answer_comments_channel.js
> +    gon.answer_ids.forEach(function (answer_id) {
Переделал.

2020-08-14 08:03 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    gon.answer_ids = answers.map(&:id) << answer.id if answer.errors.blank?
А, ну если у тебя уже все ответы загружены, то да. Но тут надо смотреть, загружены ли они.

2020-08-14 08:04 UTC, vkurennov approved these changes

2020-08-14 08:17 UTC, merged