Lesson13 cancan
smalew/qna pull request #15
Opened 2020-11-02 18:22 UTC by smalew

Реализовать все проверки в проекте на наличие прав (например, такие, что только автор может редактировать вопрос/ответ и другие правила авторизации) у пользователя через CanCan, покрыть тестами класс Ability.

2020-11-02 20:50 UTC, IvanShamatov requested changes

2020-11-02 20:50 UTC, IvanShamatov commented on app/controllers/confirmations_controller.rb
> +  skip_authorization_check only: %i[create]
check_authorization unless: :devise_controller? разве этого не достаточно, чтобы скипнуть авторизацию?

2020-11-02 20:50 UTC, IvanShamatov commented on app/controllers/links_controller.rb
> +  authorize_resource
разве указания на проверку в application controller'e не достаточно? Зачем делать это в унаследовавших контроллерах?

2020-11-02 20:50 UTC, IvanShamatov commented on app/models/user.rb
> +  def ability
так, это лишнее

2020-11-02 20:50 UTC, IvanShamatov commented on app/models/concerns/ratable.rb
> +    return if user.cannot?(:rate_down, self)
эта проверка должна проходить в контроллере (а именно в консерне rated) а не на уровне моделей. По-хорошему, как только ты вынесешь авторизацию на уровень контроллера, то смысла в этом консерне будет не много, можно всю логику тоже поместить в rated. Чего и рекомендую

2020-11-02 20:57 UTC, smalew commented on app/controllers/confirmations_controller.rb
> +  skip_authorization_check only: %i[create]
Да. Действительно. Я совсем забыл про это. 

Исправил.

2020-11-02 21:02 UTC, smalew commented on app/controllers/links_controller.rb
> +  authorize_resource
В application_controller указан check_authorization. Он как-раз проверяет, что у наследников указан authorize_resource. Иначе возвращает exception. 

Можно указать authorize_resource в application_controller. Но тогда придется "выключать" там где он не нужен. А самой проверки check_authorization не потребуется.

2020-11-02 21:09 UTC, smalew commented on app/models/user.rb
> +  def ability
Убрал

2020-11-02 21:20 UTC, smalew commented on app/models/concerns/ratable.rb
> +    return if user.cannot?(:rate_down, self)
Просмотрел код.
В приложении две модели используют код для изменения оценки (answer и question). В предыдущих занятиях мы специально выносили в концерне общую логику и применяли ее для определения функциональности моделей. Я по этому и добавлял проверку на авторство в эти методы, а в самом контроллере уже не делал этого. 

Перенес функционал проверки прав в контроллер. 
Рефакторить приложение с переносом ratable функционала в контроллер?

2020-11-02 21:29 UTC, smalew commented on app/models/concerns/ratable.rb
> +    return if user.cannot?(:rate_down, self)
Пересмотрел еще раз )

Вынес функционал полностью в контроллер. Убрал ratable конценр для моделей. Почистил тесты. 
Для контроллеров тесты уже покрывают данный функционал, по этому дописывать ничего не пришлось.

2020-11-03 05:58 UTC, IvanShamatov approved these changes

2020-11-03 18:59 UTC, merged