Lesson 5 delete question and answer
smalew/qna pull request #6
Opened 2020-06-30 18:13 UTC by smalew

3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2020-07-01 14:45 UTC, vkurennov requested changes

2020-07-01 14:45 UTC, vkurennov commented on app/models/question.rb
> +  def user_owner?(user)
дублирование. гораздо лучше перенести метод в модель User, например, назвав его author_of?, тогда можно будет в контроллерах вызывать так: `current_user.author_of?(question)`

2020-07-01 14:45 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- answers.select(&:persisted?).each do |answer|
двойная итерация по одной и той же коллекции (сначала через select, потом each), добавив условие на `persisted?` внутрь each этого можно избежать

2020-07-01 14:45 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = link_to I18n.t('answer.destroy_button'), question_answer_path(question, answer), method: :delete
1. зачем всем подряд показывать ссылку на удаление? показывай ее только автору
2. объяви ресурс answers как shallow, чтобы не приходилось передавать вопрос там, где не нужно, как, например,  здесь

2020-07-01 14:45 UTC, vkurennov commented on db/migrate/20200630195451_add_user_id_to_questions.rb
> +    add_reference :questions, :user
тут еще стоит указывать опцию `foreing_key: true`, чтобы был контроль целостности на уровне БД

2020-07-01 14:45 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
в create нужно проверить связь с залогиненным юзером

2020-07-01 14:45 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it { expect { subject }.to change(Answer, :count).by(0) }
лучше `to_not change`

2020-07-01 14:45 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it { expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0) }
лучше `to_not change`

2020-07-01 14:45 UTC, vkurennov commented on spec/factories/answers.rb
> +    association :user
кстати, если имя ассоциации и фабрики совпадает, то можно просто писать имя ассоциации, например:

```
factory :answer do
  user
  question
  ...
end
```

2020-07-01 14:45 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +          expect(page).to have_content(I18n.t('answer.successful_destroy'))
тут важно проверить, что текста ответа больше нет на странице

2020-07-01 14:45 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +          click_on I18n.t('answer.destroy_button')
а тут и далее лучше не показывать ссылку на удаление и проверять ее отсутсвие

2020-07-01 14:45 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +feature 'User can destroy question', %q{
те же замечания, что и к ответам

2020-07-01 14:45 UTC, vkurennov commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
если у тебя появляется метод в модели, нужно покрыть его тестами (в идеале, сначала тесты - потом метод)

2020-07-02 05:38 UTC, smalew commented on app/models/question.rb
> +  def user_owner?(user)
Покрыл тестами и перенес

2020-07-02 05:41 UTC, smalew commented on app/views/questions/show.html.slim
> +- answers.select(&:persisted?).each do |answer|
Готово. Перенес в `each`

2020-07-02 06:02 UTC, smalew commented on app/views/questions/show.html.slim
> +  = link_to I18n.t('answer.destroy_button'), question_answer_path(question, answer), method: :delete
Добавил условия и переделал роутинг.

2020-07-02 06:03 UTC, smalew commented on db/migrate/20200630195451_add_user_id_to_questions.rb
> +    add_reference :questions, :user
Добавил.

2020-07-02 06:10 UTC, smalew commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Проверка добавлена в контроллеры.

2020-07-02 06:11 UTC, smalew commented on spec/factories/answers.rb
> +    association :user
Поправил

2020-07-02 06:12 UTC, smalew commented on spec/features/answer/destroy_spec.rb
> +          expect(page).to have_content(I18n.t('answer.successful_destroy'))
Добавил проверку.

2020-07-02 06:13 UTC, smalew commented on spec/features/answer/destroy_spec.rb
> +          click_on I18n.t('answer.destroy_button')
Поправил и добавил проверку.

2020-07-02 06:14 UTC, smalew commented on spec/features/question/destroy_spec.rb
> +feature 'User can destroy question', %q{
Привел тест в порядок.

2020-07-02 06:15 UTC, smalew commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
Метод пренадлежности к пользователю переехал в модель User.
Я сначала написал тест и потом добавил метод.

2020-07-02 08:53 UTC, vkurennov approved these changes

2020-07-02 08:53 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.author_of?(question)
чтобы не писать составное условие, можно использовать [safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

2020-07-02 08:53 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +          expect(page).to have_content(I18n.t('answer.successful_destroy'))
ссылки лучше через have_link проверять, но не критично

2020-07-02 08:53 UTC, vkurennov commented on spec/models/user_spec.rb
> +          it { expect(user.author_of?(question)).to be_truthy }
есть более красивый синтаксис: `expect(user).to be_author_of(question)`
работает для любого метода-предиката: просто пренеосим вызов метода после to/to_not, добавляем be_ и убираем знак вопроса

2020-07-02 08:53 UTC, vkurennov commented on spec/models/user_spec.rb
> +        context 'answer' do
у тебя метод универсальный и не зависит от типа аргумента. по идее, достаточно, чтобы у объекта был user_id. поэтому не нужно проверять его на каждом возможном типе, лучше проверить на объекте, у которого нет user_id, чтобы метод не падал (хотя тут спорно, возможно, он и должен падать в таком случае). в общем, достаточно только на одном типе аргумента проверить

2020-07-02 16:36 UTC, smalew commented on spec/controllers/answers_controller_spec.rb
> +      it { expect { subject }.to change(Answer, :count).by(0) }
Точно. Совсем забыл. Поправил

2020-07-02 16:36 UTC, smalew commented on spec/controllers/questions_controller_spec.rb
> +      it { expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0) }
Поправил

2020-07-02 16:40 UTC, smalew commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.author_of?(question)
Мне показалась такая проверка более приятной глазу. 

Переделал.

2020-07-02 16:43 UTC, smalew commented on spec/features/answer/destroy_spec.rb
> +          expect(page).to have_content(I18n.t('answer.successful_destroy'))
Надо лучше читать документацию... Исправил.

2020-07-02 16:47 UTC, smalew commented on spec/models/user_spec.rb
> +          it { expect(user.author_of?(question)).to be_truthy }
А вот это просто огонь какая классная фича. Исправил.

2020-07-02 16:56 UTC, smalew commented on spec/models/user_spec.rb
> +        context 'answer' do
Сделал заглушку с помощью Struct и проверяю еще и на наличие метода у объекта. Передлал на более абстрактный тест.

2020-07-02 16:58 UTC, merged