Lesson 7 ajax completed
smalew/qna pull request #8
Opened 2020-07-04 10:37 UTC by smalew

2. Используя ajax, реализовать следующие истории и задачи:

  - Только автор может отредактировать свой вопрос
  - Только автор может отредактировать свой ответ
  - Переделать удаление ответов на ajax
  - Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1)
  - Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ (предыдущий лучший ответ перестает быть таковым)
  - Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

2020-07-04 11:51 UTC, vkurennov requested changes

2020-07-04 11:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.update(answer_params)
по заданию, только автор может менять ответ, поэтому здесь нужна проверка на автора, как в destroy

2020-07-04 11:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    question.update(best_answer: answer) if current_user.author_of?(question)
вот тут не очень удачная архитектура решения, хотя на первый взгляд, отвечает всем требованиям. во-первых, здесь идет инвертация и дублирование ассоциаций: ответы и так уже принадлежат вопросом, при этом вопрос является "родительским" по отношению к вопросу, добавляя ассоциацию с лучшим ответом, уже вопрос становится "подчиненным" к ответу, ну и связь устанавливается еще раз.
Лучше это организовать через флаг у ответа

2020-07-04 11:51 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    question.update(question_params)
тут тоже нужна проверка на автора

2020-07-04 11:51 UTC, vkurennov commented on app/views/answers/choose_as_best.js.erb
> +$('#best-answer').html('<%= j answer.body %>');
тогда ответ будет и в общем списке и в блоке лучшего, т.е. дважды на странице

2020-07-04 11:51 UTC, vkurennov commented on app/views/answers/create.js.erb
> +  $('.answers').append("<div id='answer-id-<%= answer.id %>'><%= j render answer %></div>")
стоит div с id ответа поместить в паршл ответа, чтобы не нужно было здесь его дополнительно добавлять

2020-07-04 11:51 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe '#PATCH update' do
тут должны быть контесты для автора и для не-автора

2020-07-06 05:36 UTC, smalew commented on app/controllers/answers_controller.rb
> +    answer.update(answer_params)
Добавил проверку.

2020-07-06 05:54 UTC, smalew commented on app/controllers/answers_controller.rb
> +    question.update(best_answer: answer) if current_user.author_of?(question)
Добавил в модель answers булево поле `best_answer` и переделал тесты с логикой.

2020-07-06 05:58 UTC, smalew commented on app/controllers/questions_controller.rb
> +    question.update(question_params)
Проверка и тесты добавлены.

2020-07-06 06:29 UTC, smalew commented on app/views/answers/choose_as_best.js.erb
> +$('#best-answer').html('<%= j answer.body %>');
Я еще думал убирать лучший ответ из списка ответов или нет. В задании об этом расплывчато сказано. 

Переделал. тесты и убрал из общего списка.

2020-07-06 06:32 UTC, smalew commented on app/views/answers/create.js.erb
> +  $('.answers').append("<div id='answer-id-<%= answer.id %>'><%= j render answer %></div>")
Я об этом тоже думал. Но если в паршл переносить, то при замене пользователя получается вложенность 

```
<div id='answer-id-1>
  <div id='answer-id-1>
    ...
  </div>
</div>
```
Это же не очень. 
Есть какая-то дока или метод для js? А то я в нем не очень. 
Возможно полностью удалять элемент и вставлять его заново? о_0

2020-07-06 06:34 UTC, smalew commented on spec/controllers/questions_controller_spec.rb
>    describe '#PATCH update' do
Добавил.

2020-07-06 10:59 UTC, vkurennov requested changes

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(question)
этому не место в контроллере, это же бизнес-логика. а ее мы храним на уровне моделей. вынеси это в метод модели и не забудь на них написать тесты

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @best_answer&.update(best_answer: false)
а вот тут, раз несколько одновременных изменений, нужно применить транзакцию, чтобы изменения были атомарными

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.update(answer_params) if current_user.author_of?(answer)
а что будет рендериться, если условие не выполнится?

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.destroy if current_user.author_of?(answer)
что будет рендериться, если условие не выполнится?

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(question)
что будет рендериться, если условие не выполнится?

2020-07-06 10:59 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    question.update(question_params) if current_user.author_of?(question)
что будет рендериться, если условие не выполнится?

2020-07-06 10:59 UTC, vkurennov commented on app/views/answers/choose_as_best.js.erb
> +  $('.answers').append("<div id='answer-id-<%= @best_answer.id %>'><%= j render @best_answer %></div>")
а зачем его аппендить? он же уже есть на странице. тут можно просто повтороно весь список отрендерить, только чтобы лучший уже был первым.

2020-07-06 10:59 UTC, vkurennov commented on app/views/answers/create.js.erb
> +  $('.answers').append("<div id='answer-id-<%= answer.id %>'><%= j render answer %></div>")
такая проблема только при апдейте может быть, при создании никак не может вложенного div получиться, ведь его еще нет на странице. Ну либо если ты div и тут оставляешь и в паршл добавляешь, но тут решение простое - только в одном месте оставить div. А для апдейта подойдет функция [html()](https://api.jquery.com/html/)

2020-07-06 17:32 UTC, smalew commented on app/views/answers/create.js.erb
> +  $('.answers').append("<div id='answer-id-<%= answer.id %>'><%= j render answer %></div>")
Исправил.

2020-07-06 17:33 UTC, smalew commented on app/controllers/answers_controller.rb
> +      @best_answer&.update(best_answer: false)
Реализовал.

2020-07-06 17:34 UTC, smalew commented on app/views/answers/choose_as_best.js.erb
> +  $('.answers').append("<div id='answer-id-<%= @best_answer.id %>'><%= j render @best_answer %></div>")
Переделал.

2020-07-06 18:36 UTC, smalew commented on app/controllers/answers_controller.rb
> +    answer.update(answer_params) if current_user.author_of?(answer)
Если я правильно понял вопрос, то переделал на рендеринг question_show.

2020-07-06 18:46 UTC, smalew commented on app/controllers/questions_controller.rb
> +    question.update(question_params) if current_user.author_of?(question)
Переделал.

2020-07-06 18:46 UTC, smalew commented on app/controllers/answers_controller.rb
> +    answer.destroy if current_user.author_of?(answer)
Переделал.

2020-07-06 18:55 UTC, smalew commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(question)
Отрендерится список вопросов в js файле. Только без изменения статутов. 

Или подразумевается, что необходимо:
1. Перенести всю логику в модель, включая проверку на авторство? 
2. Добавить валидацию, что бы обект содержал error и этот error выводить на странице?

2020-07-07 09:01 UTC, vkurennov approved these changes

2020-07-07 09:01 UTC, vkurennov commented on spec/features/question/choose_best_answer_spec.rb
> +            expect(page).to have_content(answer.body)
не очень полноценная проверка, ведь ответ и так на странице присутсвует, вне зависимости от того, лучший он или нет. т.е. тест не проверяет, что он стал лучшим. можно, например, проверить, что он первый в списке или, что имеет  какой-то особый класс или шильдик

2020-07-07 18:35 UTC, smalew commented on app/models/answer.rb
> +    Answer.transaction do
Точно. Совсем забыл. Исправил.

2020-07-07 18:36 UTC, smalew commented on spec/features/question/choose_best_answer_spec.rb
> +            expect(page).to have_content(answer.body)
Точно. Спасибо за наводку. Добавлю для лучшего ответа ID. 

Переделал.

2020-07-07 18:48 UTC, merged